services:
  backend:
    build: .
    command: poetry run python backend/src/manage.py migrate && poetry run python backend/src/manage.py runserver 
    volumes:
      - ./:/app
    restart: unless-stopped
    network_mode: 'host'

  load_balancer:
    image: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/app/frontend
      - /etc/letsencrypt:/etc/letsencrypt/
    depends_on:
      - backend
    network_mode: 'host'
