services:
  backend:
    build: .
    command: poetry run python manage.py migrate && python manage.py runserver 
    volumes:
      - ./:/app
      - uploads:/app/uploads
    restart: unless-stopped
    network_mode: 'host'

  load_balancer:
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/app/frontend
      - /etc/letsencrypt:/etc/letsencrypt/
    depends_on:
      - backend
    network_mode: 'host'
