# Generated by Django 5.1.4 on 2024-12-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_password',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Пароль студента'),
        ),
    ]
